# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Samlaf's Homepage
author: Samuel Laferriere
email: samlaf92 [at] gmail [dot] com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my website, where I hope to lay down my projects,
  thoughts and ideas. Currently under construction.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: samlafer
github_username:  samlaf

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
collections:
  projects:
    output: true
    # This ordering isn't working...
    order:
      - 2020-06-12-manifold-optimization.md
      - 2018-01-11-duckietown-slam.md
      - 2018-05-21-reproducibility-report.md
      - 2017-11-20-reproducibility-agave.md


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# These are front matter defaults. These make it so that we don't need to add the "layout" front matter to projects and posts.
# See https://jekyllrb.com/docs/step-by-step/09-collections/ for more details.
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"